secretGenerator:
- name: redis-config
  files:
  - redis.conf
- name: postgres-config
  envs:
  - postgres.env
- name: app-config
  files:
  - app.env

namePrefix: forumal-dev-
resources:
  - ../../base
  - postgres.yaml
  - redis.yaml
patches:
  - path: dev-image.yaml
  - path: dev-service.yaml