apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-app
  template:
    metadata:
      labels:
        app: next-app
    spec:
      containers:
        - name: next-app
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3000
          volumeMounts:
          - mountPath: /app/.env
            name: config
            subPath: app.env
      volumes:
        - name: config
          secret:
            secretName: app-config
