apiVersion: v1
kind: Service
metadata:
  name: next-app
  labels:
    app: next-app
# Doing ClusterIP here, overriding with NodePort for dev purposes; "prod" needs an Ingress or Gateway
spec:
  selector:
   app: next-app